# Generated by Django 2.2.4 on 2019-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereço',
            name='Bairro',
            field=models.CharField(default='tirol', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereço',
            name='Cep',
            field=models.CharField(default='12345678', max_length=8),
            preserve_default=False,
        ),
    ]
